### PR TITLE
Add MLJ compliant doc-strings - take II

### PR DESCRIPTION
**Pull request by ablaom**
Replaces #22 

@pazzo83 I have a reviewed the original PR, to ensure compliance with the new MLJ standard, but have also made some changes of my own (which involve some paring down of your original strings).  Would you have time in the next few weeks to do a final review? 

I suggest one begins by looking over the final docstrings generated by a `julia> ?` query, as some of the interpolation magic makes it hard to catch all mistakes by just reading code.

cc @JosephsDavid

### CODE REVIEW

**Comment by pazzo83** [comment]
Yes I will take a look this week!  Thanks!

**Comment by ablaom** [comment]
@pazzo83 Do you still have some time to look over this?

**Comment by pazzo83** [comment]
I am going to try to look at it this weekend!

**Comment by pazzo83** [comment]
Again sorry for the delay here!  This looks good!  Should I merge?

**Review by pazzo83 — APPROVED** [review]
Looks great!  We might need to update some of the package versions in requirements?

**Comment by ablaom** [comment]
> We might need to update some of the package versions in requirements?

I've kicked CompatHelper out of hibernation and all looks good.

**Pull request merged**
